apiVersion: v1
kind: Secret
metadata:
  name: globeco-order-generation-service-secrets
  namespace: globeco
  labels:
    app: globeco-order-generation-service
    component: order-generation
    version: v1
    tier: application
type: Opaque
data:
  # MongoDB connection URL (base64 encoded)
  # mongodb://globeco-order-generation-service-mongodb:27017/globeco_production
  mongodb-url: bW9uZ29kYjovL2dsb2JlY28tb3JkZXItZ2VuZXJhdGlvbi1zZXJ2aWNlLW1vbmdvZGI6MjcwMTcvZ2xvYmVjb19wcm9kdWN0aW9u

  # Application secret key for JWT and security (base64 encoded)
  # production-secret-key-change-in-production
  secret-key: cHJvZHVjdGlvbi1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
---
apiVersion: v1
kind: Secret
metadata:
  name: globeco-order-generation-service-mongodb-credentials
  namespace: globeco
  labels:
    app: globeco-order-generation-service
    component: order-generation
    version: v1
    tier: database
type: Opaque
data:
  # MongoDB credentials (base64 encoded)
  # username: ordgen_user
  username: b3JkZ2VuX3VzZXI=
  # password: ordgen_secure_password_123
  password: b3JkZ2VuX3NlY3VyZV9wYXNzd29yZF8xMjM=
  # root-password: mongodb_root_password_456
  root-password: bW9uZ29kYl9yb290X3Bhc3N3b3JkXzQ1Ng==
