apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: globeco-order-generation-service-hpa
  namespace: globeco
  labels:
    app: globeco-order-generation-service
    component: order-generation
    version: v1
    tier: application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globeco-order-generation-service
  minReplicas: 3
  maxReplicas: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
  metrics:
  # CPU utilization target
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory utilization target
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics (if Prometheus adapter is available)
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "10"
  - type: Pods
    pods:
      metric:
        name: optimization_queue_length
      target:
        type: AverageValue
        averageValue: "5"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: globeco-order-generation-service-pdb
  namespace: globeco
  labels:
    app: globeco-order-generation-service
    component: order-generation
    version: v1
    tier: application
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: globeco-order-generation-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: globeco-order-generation-service
  namespace: globeco
  labels:
    app: globeco-order-generation-service
    component: order-generation
    version: v1
    tier: application
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: globeco-order-generation-service-role
  namespace: globeco
  labels:
    app: globeco-order-generation-service
    component: order-generation
    version: v1
    tier: application
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: globeco-order-generation-service-rolebinding
  namespace: globeco
  labels:
    app: globeco-order-generation-service
    component: order-generation
    version: v1
    tier: application
subjects:
- kind: ServiceAccount
  name: globeco-order-generation-service
  namespace: globeco
roleRef:
  kind: Role
  name: globeco-order-generation-service-role
  apiGroup: rbac.authorization.k8s.io
