apiVersion: apps/v1
kind: Deployment
metadata:
  name: globeco-order-generation-service
  namespace: globeco
  labels:
    app: globeco-order-generation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globeco-order-generation-service
  template:
    metadata:
      labels:
        app: globeco-order-generation-service
    spec:
      containers:
        - name: globeco-order-generation-service
          image: kasbench/globeco-order-generation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: MONGODB_URL
              value: "mongodb://globeco-order-generation-service-mongodb"
            - name: DATABASE_NAME
              value: "prod"
            - name: SECRET_KEY
              value: "globeco-order-generation-service-secret-key"
            - name: OTEL_METRICS_LOGGING_ENABLED
              value: "false"
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "2000m"
              memory: "2000Mi"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 240
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          # startupProbe:
          #   httpGet:
          #     path: /
          #     port: 8088
          #   failureThreshold: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: globeco-order-generation-service
  namespace: globeco
spec:
  selector:
    app: globeco-order-generation-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
