apiVersion: apps/v1
kind: Deployment
metadata:
  name: globeco-order-generation-service
  namespace: globeco
  labels:
    app: globeco-order-generation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globeco-order-generation-service
  template:
    metadata:
      labels:
        app: globeco-order-generation-service
    spec:
      containers:
        - name: globeco-order-generation-service
          image: kasbench/globeco-order-generation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          env:
            - name: MONGODB_URL
              value: "mongodb://globeco-order-generation-service-mongodb"
            - name: DATABASE_NAME
              value: "prod"
            - name: SECRET_KEY
              value: "globeco-order-generation-service-secret-key"
            - name: OTEL_METRICS_LOGGING_ENABLED
              value: "false"
            - name: LOG_LEVEL
              value: "INFO"
            # OpenTelemetry Configuration using node-local collector
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_COLLECTOR_GRPC_ENDPOINT
              value: "$(NODE_IP):4317"
            - name: OTEL_COLLECTOR_HTTP_ENDPOINT
              value: "http://$(NODE_IP):4318"
            - name: OTEL_INSECURE
              value: "true"
            # Inject the node and pod metadata from the Downward API
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace


            # Define standard service identity attributes
            - name: OTEL_SERVICE_NAME
              value: "globeco-order-generation-service"
            - name: OTEL_SERVICE_NAMESPACE
              value: "globeco"

            # Inject Kubernetes metadata as resource attributes for k8sattributes processor
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: >-
                k8s.pod.ip=$(MY_POD_IP),
                k8s.pod.name=$(MY_POD_NAME),
                k8s.node.name=$(MY_NODE_NAME),
                k8s.namespace.name=$(MY_NAMESPACE)
          resources:
            requests:
              cpu: "500m"
              memory: "200Mi"
            limits:
              cpu: "2000m"
              memory: "2000Mi"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8088
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/ready
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 12
          # startupProbe:
          #   httpGet:
          #     path: /
          #     port: 8088
          #   failureThreshold: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: globeco-order-generation-service
  namespace: globeco
spec:
  selector:
    app: globeco-order-generation-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
