apiVersion: v1
kind: Service
metadata:
  name: globeco-order-generation-service-mongodb
  namespace: globeco
  labels:
    app: globeco-order-generation-service-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: globeco-order-generation-service-mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: globeco-order-generation-service-mongodb
  namespace: globeco
spec:
  serviceName: globeco-order-generation-service-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: globeco-order-generation-service-mongodb
  template:
    metadata:
      labels:
        app: globeco-order-generation-service-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: order-generation-service-mongodb-data
              mountPath: /data/db
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
  volumeClaimTemplates:
    - metadata:
        name: order-generation-service-mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-storage
