apiVersion: v1
kind: Service
metadata:
  name: globeco-order-generation-service-redis
  namespace: globeco
  labels:
    app: globeco-order-generation-service-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: globeco-order-generation-service-redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: globeco-order-generation-service-redis
  namespace: globeco
spec:
  serviceName: globeco-order-generation-service-redis
  replicas: 1
  selector:
    matchLabels:
      app: globeco-order-generation-service-redis
  template:
    metadata:
      labels:
        app: globeco-order-generation-service-redis
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
        storageClassName: local-storage
