{
  "openapi": "3.1.0",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8083",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/v1/prices": {
      "get": {
        "tags": [
          "price-controller"
        ],
        "operationId": "getAllPrices",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/PriceDto"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/price/{ticker}": {
      "get": {
        "tags": [
          "price-controller"
        ],
        "operationId": "getPriceByTicker",
        "parameters": [
          {
            "name": "ticker",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/PriceDto"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "PriceDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "ticker": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "format": "date"
          },
          "open": {
            "type": "number"
          },
          "close": {
            "type": "number"
          },
          "high": {
            "type": "number"
          },
          "low": {
            "type": "number"
          },
          "volume": {
            "type": "integer",
            "format": "int64"
          }
        }
      }
    }
  }
}
Ask