groups:
  - name: globeco_alerts
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up{job="globeco-order-generation"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "GlobeCo Order Generation Service is down"
          description: "The GlobeCo Order Generation Service has been down for more than 1 minute."

      # High response time alerts
      - alert: HighResponseTime
        expr: http_request_duration_seconds{quantile="0.95"} > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for endpoint {{ $labels.endpoint }}"

      # High error rate alerts
      - alert: HighErrorRate
        expr: rate(http_requests_total{status_code=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for endpoint {{ $labels.endpoint }}"

      # Optimization failure alerts
      - alert: OptimizationFailures
        expr: rate(optimizations_total{status="error"}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High optimization failure rate"
          description: "Optimization failure rate is {{ $value }} failures per second"

      # Memory usage alerts
      - alert: HighMemoryUsage
        expr: memory_usage_bytes / (1024 * 1024 * 1024) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanize }}GB"

      # CPU usage alerts
      - alert: HighCPUUsage
        expr: cpu_usage_percent > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      # Active connections alerts
      - alert: TooManyActiveConnections
        expr: active_connections > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many active connections"
          description: "There are {{ $value }} active connections"
