global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Main application metrics
  - job_name: 'globeco-order-generation'
    static_configs:
      - targets: ['host.docker.internal:8189']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Health check monitoring
  - job_name: 'globeco-health'
    static_configs:
      - targets: ['host.docker.internal:8189']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  # MongoDB metrics (if enabled)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['host.docker.internal:27020']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
