apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-generation-service-mongodb-pvc
  namespace: globeco
  labels:
    app: order-generation-service-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 10Gi
